name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      APP_URL: ${{ secrets.APP_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install TypeScript
        run: npm install --save-dev typescript


      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report-${{ matrix.os }}
          path: playwright-report/
          retention-days: 7
      - name: Upload Playwright test artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: playwright-test-results-${{ matrix.os }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: allure-results-${{ matrix.os }}
          path: allure-results/
          if-no-files-found: ignore
          retention-days: 7
